# Generated by Django 6.0 on 2025-12-07 13:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('media_id', models.CharField(max_length=255)),
                ('button', models.CharField(choices=[('ALL_CATEGORIES', 'ALL_CATEGORIES'), ('MY_PROFILE', 'MY_PROFILE'), ('FAQ', 'FAQ'), ('HELP', 'HELP'), ('CART', 'CART'), ('MENU', 'MENU')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'buttons_media',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('media_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_datetime', models.DateTimeField()),
                ('expire_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=1)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('media_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('telegram_username', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('top_up_amount', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=36, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('consume_records', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=36, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('can_receive_messages', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('UZ', 'Uzbek'), ('fr', 'Fr'), ('de', 'De'), ('it', 'It'), ('zh', 'Zh'), ('ar', 'Ar'), ('es', 'Es'), ('ja', 'Ja')], default='EN', max_length=2)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=12, max_digits=36, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))])),
                ('buy_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buys', to='products.coupon')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buys', to='products.user')),
            ],
            options={
                'db_table': 'buys',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('private_data', models.TextField()),
                ('price', models.DecimalField(decimal_places=12, max_digits=36, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))])),
                ('is_sold', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.subcategory')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='BuyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_items', to='products.buy')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_buy_items', to='products.item')),
            ],
            options={
                'db_table': 'buyItem',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.cart')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.subcategory')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('processing_payment_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('expire_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='products.user')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('network', models.CharField(choices=[('BNB', 'Bnb'), ('BTC', 'Btc'), ('LTC', 'Ltc'), ('ETH', 'Eth'), ('SOL', 'Sol')], max_length=20)),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('deposit_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='products.user')),
            ],
            options={
                'db_table': 'deposits',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.user'),
        ),
    ]
