# Generated by Django 6.0 on 2025-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='buttonmedia',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', null=True, verbose_name='Modified At'),
        ),
    ]
